// packages/gcode-preview-react/src/model/model-viewer-component.ts
/**
 * <ModelViewer> — the ready-to-use React component for interactive source-model viewing (STL / 3MF),
 * the Prepare-side counterpart to <GcodePreview> (DD-031). A SHELL over `useModelViewer`: every prop
 * maps to a controls call, every callback re-fires a controller event, and the full handle is reachable
 * via `ref`. `<ModelViewer source={file} />` alone is a working viewer.
 *
 * createElement (no JSX) on purpose — the template is a single full-size <canvas>.
 */
import {
  createElement,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type ForwardedRef,
  type ReactElement
} from 'react';
import type {
  CameraMode,
  CameraState,
  CameraView,
  GLRendererLike,
  InteractiveStageOptions,
  LoadProgress,
  RenderTargetCanvas
} from '@chestnutlabs/gcode-renderer-three';
import type {
  ModelBackground,
  ModelLimits,
  ModelLoader,
  ModelReadyInfo,
  ModelSourceInput,
  ModelViewerEvent,
  PresentationView,
  RenderScope
} from '@chestnutlabs/gcode-model-renderer';
import { useModelViewer, type ModelViewerHandle } from './use-model-viewer.js';

export type ModelViewerSource = ModelSourceInput | null;

export interface ModelViewerProps {
  /** The one prop needed in practice: the source model. Changing it re-parses. */
  source?: ModelViewerSource;
  /** Snap to a preset orientation (shared vocabulary with the toolpath camera). */
  view?: PresentationView | CameraView;
  /** Restore a saved camera pose. Pair with `onCameraChange` for a two-way binding. */
  cameraState?: CameraState | null;
  /** `'transparent'` (default) | CSS colour | `0xRRGGBB`. */
  background?: ModelBackground;
  /** DD-020 interaction-aware quality; default `'auto'`. */
  interactionQuality?: 'off' | 'auto';
  /** Initial camera projection; default `'perspective'`. */
  cameraMode?: CameraMode;
  /** Render only a subset: `{ plateId }` / `{ objectIds }` / `{ instanceFilter }`; null = whole source. */
  renderScope?: RenderScope | null;
  /** Source-model triangle / byte caps. */
  limits?: ModelLimits;
  /** 3MF `paint_color` palette override (hex per 0-based slot). */
  filamentPalette?: readonly (string | undefined)[];
  /** Loader registry (open `kind`). Default: STL + 3MF. */
  loaders?: readonly ModelLoader[];
  /** Advanced/test: inject GL / orbit controls. */
  createRenderer?: (canvas: RenderTargetCanvas) => GLRendererLike;
  createControls?: NonNullable<InteractiveStageOptions['createControls']>;
  onReady?: (info: ModelReadyInfo) => void;
  onCameraChange?: (state: CameraState) => void;
  onError?: (e: { code: string; message: string }) => void;
  onRendererUnsupported?: (e: { feature: string; message: string }) => void;
  onContextLost?: () => void;
  onContextRestored?: () => void;
  onProgress?: (progress: LoadProgress) => void;
}

function ModelViewerImpl(props: ModelViewerProps, ref: ForwardedRef<ModelViewerHandle>): ReactElement {
  const {
    source = null,
    view,
    cameraState,
    background,
    interactionQuality,
    cameraMode,
    renderScope,
    limits,
    filamentPalette,
    loaders,
    createRenderer,
    createControls
  } = props;

  // Construction-time options (stable for the controller's lifetime).
  const viewer = useModelViewer({
    ...(background !== undefined ? { background } : {}),
    ...(interactionQuality !== undefined ? { interactionQuality } : {}),
    ...(cameraMode !== undefined ? { cameraMode } : {}),
    ...(limits !== undefined ? { limits } : {}),
    ...(filamentPalette !== undefined ? { filamentPalette } : {}),
    ...(loaders !== undefined ? { loaders } : {}),
    ...(renderScope != null ? { renderScope } : {}),
    ...(createRenderer !== undefined ? { createRenderer } : {}),
    ...(createControls !== undefined ? { createControls } : {}),
    onProgress: (p) => cbRef.current.onProgress?.(p)
  });

  useImperativeHandle(ref, () => viewer, [viewer]);

  // Latest callbacks without re-subscribing the event bridge.
  const cbRef = useRef(props);
  cbRef.current = props;

  useEffect(() => {
    return viewer.onEvent((e: ModelViewerEvent) => {
      const cb = cbRef.current;
      switch (e.type) {
        case 'ready':
          cb.onReady?.(e.info);
          break;
        case 'camera-changed':
          cb.onCameraChange?.(e.state);
          break;
        case 'error':
          cb.onError?.({ code: e.code, message: e.message });
          break;
        case 'renderer-unsupported':
          cb.onRendererUnsupported?.({ feature: e.feature, message: e.message });
          break;
        case 'context-lost':
          cb.onContextLost?.();
          break;
        case 'context-restored':
          cb.onContextRestored?.();
          break;
        default:
          break;
      }
    });
  }, [viewer]);

  // ---- runtime prop wiring (each a thin controls call) ----
  useEffect(() => {
    if (source !== null && source !== undefined) void viewer.controls.setSource(source);
  }, [viewer, source]);
  useEffect(() => {
    if (view !== undefined) viewer.controls.setView(view);
  }, [viewer, view]);
  useEffect(() => {
    if (cameraState !== undefined && cameraState !== null) viewer.controls.setCameraState(cameraState);
  }, [viewer, cameraState]);
  useEffect(() => {
    if (background !== undefined) viewer.controls.setBackground(background);
  }, [viewer, background]);
  useEffect(() => {
    if (interactionQuality !== undefined) viewer.controls.setInteractionQuality(interactionQuality);
  }, [viewer, interactionQuality]);
  useEffect(() => {
    if (renderScope !== undefined) viewer.controls.setRenderScope(renderScope);
  }, [viewer, renderScope]);

  return createElement('canvas', {
    ref: viewer.canvasRef,
    style: { width: '100%', height: '100%', display: 'block', touchAction: 'none' },
    tabIndex: 0,
    'aria-label': '3D source-model preview'
  });
}

export const ModelViewer = forwardRef(ModelViewerImpl);

// packages/gcode-preview-svelte/src/model/ModelViewer.svelte
<script>
  /**
   * <ModelViewer> — the ready-to-use Svelte component for interactive source-model viewing (STL / 3MF),
   * the Prepare-side counterpart to <GcodePreview> (DD-031). A SHELL over `createModelViewer` (the
   * Svelte store/action handle): every prop is a reactive statement into the handle, every dispatched
   * event re-fires a controller event, and the handle is exported for bind:this access (`viewer`).
   * `<ModelViewer source={file} />` alone is a working viewer.
   *
   * Shipped RAW — the consumer's bundler compiles it via the "svelte" export condition.
   */
  import { createEventDispatcher, onDestroy } from 'svelte';
  import { createModelViewer } from './create-model-viewer.js';

  /** The source model. Changing it re-parses. */
  export let source = null;
  /** Snap to a preset orientation (shared vocabulary with the toolpath camera). */
  export let view = undefined;
  /** Restore a saved camera pose. Pair with the `camerachange` event for two-way binding. */
  export let cameraState = undefined;
  /** 'transparent' (default) | CSS colour | 0xRRGGBB. */
  export let background = undefined;
  /** DD-020 interaction-aware quality; default 'auto'. */
  export let interactionQuality = undefined;
  /** Initial camera projection; default 'perspective'. */
  export let cameraMode = undefined;
  /** Render only a subset: { plateId } / { objectIds } / { instanceFilter }; null = whole source. */
  export let renderScope = undefined;
  /** Source-model triangle / byte caps. */
  export let limits = undefined;
  /** 3MF paint_color palette override (hex per 0-based slot). */
  export let filamentPalette = undefined;
  /** Loader registry (open kind). Default: STL + 3MF. */
  export let loaders = undefined;
  /** Advanced/test: inject GL / orbit controls. */
  export let createRenderer = undefined;
  export let createControls = undefined;

  const dispatch = createEventDispatcher();

  /** The full store/action handle — reachable via bind:this={c} then c.viewer. */
  export const viewer = createModelViewer({
    background,
    interactionQuality,
    cameraMode,
    limits,
    filamentPalette,
    loaders,
    renderScope,
    createRenderer,
    createControls,
    onProgress: (p) => dispatch('progress', p)
  });

  viewer.onEvent((e) => {
    switch (e.type) {
      case 'ready':
        dispatch('ready', e.info);
        break;
      case 'camera-changed':
        dispatch('camerachange', e.state);
        break;
      case 'error':
        dispatch('error', { code: e.code, message: e.message });
        break;
      case 'renderer-unsupported':
        dispatch('rendererunsupported', { feature: e.feature, message: e.message });
        break;
      case 'context-lost':
        dispatch('contextlost');
        break;
      case 'context-restored':
        dispatch('contextrestored');
        break;
      default:
        break;
    }
  });

  // ---- prop wiring: each prop is a thin reactive call into the handle (D1 shell rule) ----
  $: if (source !== null && source !== undefined) void viewer.controls.setSource(source);
  $: if (view !== undefined) viewer.controls.setView(view);
  $: if (cameraState !== undefined && cameraState !== null) viewer.controls.setCameraState(cameraState);
  $: if (background !== undefined) viewer.controls.setBackground(background);
  $: if (interactionQuality !== undefined) viewer.controls.setInteractionQuality(interactionQuality);
  $: if (renderScope !== undefined) viewer.controls.setRenderScope(renderScope);

  onDestroy(() => viewer.dispose());
</script>

<!-- tabindex makes the canvas focusable → keyboard camera (DD-004 a11y) -->
<canvas
  use:viewer.canvas
  tabindex="0"
  style="width: 100%; height: 100%; display: block; touch-action: none;"
  aria-label="3D source-model preview"
></canvas>
