// tools/example-react/src/showcase.jsx
/*
 * Full showcase example (DD-031 §4.7, tier 2).
 *
 * Exercises the real declarative surface of @chestnutlabs/gcode-preview-react and mirrors the
 * Feature Lab's capability-aware UX in React idiom: color modes gate on the file's capabilities
 * with a plain-language reason, feature-role hiding is a declarative prop, and diagnostics/picking
 * come through the ref handle's `controls`. Chrome (light/dark) is separate from the renderer's
 * neutral viewport. Styling is the shared workspace-internal demo-kit — not a published UI kit and
 * not a library default. Still the real package: no raw renderer or parser imports.
 */
import { StrictMode, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { GcodePreview } from '@chestnutlabs/gcode-preview-react';
import { FeatureRole } from '@chestnutlabs/toolpath-core';
import {
  FIXTURE_GROUPS,
  FIXTURE_BY_ID,
  COLOR_MODES,
  COLOR_MODE_BY_ID,
  colorModeReason,
  confidenceTier,
  rgbCss,
  count as formatCount,
  duration as formatDuration
} from '../../demo-kit/index.js';
import '../../demo-kit/tokens.css';

const ADHESION_ROLES = [FeatureRole.Skirt, FeatureRole.Brim];
const CAM_VIEWS = [
  ['iso', 'Iso'],
  ['top', 'Top'],
  ['front', 'Front']
];

function App() {
  const ref = useRef(null);
  const [chrome, setChrome] = useState('dark');
  const [fixtureId, setFixtureId] = useState('skirt-brim');
  const [source, setSource] = useState(null);

  // Reactive UI state, mirrored from the component's event callbacks (the controlled-component idiom).
  const [caps, setCaps] = useState({});
  const [layers, setLayers] = useState(0);
  const [segments, setSegments] = useState(0);
  const [topLayer, setTopLayer] = useState(0);
  const [disclosure, setDisclosure] = useState('');
  const [hasRetractions, setHasRetractions] = useState(false);
  const [time, setTime] = useState({ ms: null, src: null });
  const [stats, setStats] = useState(null);
  const [picked, setPicked] = useState(null);

  // Declarative control props.
  const [colorModeId, setColorModeId] = useState('feature');
  const [hideAdhesion, setHideAdhesion] = useState(false);
  const [showTravel, setShowTravel] = useState(false);
  const [showRetractions, setShowRetractions] = useState(false);
  const [view, setView] = useState('iso');

  document.documentElement.dataset.chrome = chrome;

  const mode = COLOR_MODE_BY_ID[colorModeId];
  const modeReason = colorModeReason(colorModeId, caps);
  const colorMode = modeReason === '' ? mode.build() : undefined; // don't apply an unavailable mode
  const legend = mode.legend ?? (colorModeId === 'feature' ? COLOR_MODE_BY_ID.feature.legend : null);
  const featureRolesKnown = caps.featureRoles === 'known' || caps.featureRoles === 'inferred';

  async function load(id) {
    const fx = FIXTURE_BY_ID[id];
    if (!fx) return;
    setFixtureId(id);
    const res = await fetch(`./${fx.path}`);
    setSource(new Uint8Array(await res.arrayBuffer()));
    setStats(null);
    setPicked(null);
  }

  function onReady(s) {
    if (typeof window !== 'undefined') window.gcodePreview = ref.current; // handle, for devtools/inspection
    setCaps(s.capabilities);
    setLayers(s.layers);
    setSegments(s.segments);
    setTopLayer(Math.max(0, s.layers - 1));
    // Pull the reactive fields the ready summary doesn't carry from the live state snapshot.
    const st = ref.current?.state;
    if (st) {
      setHasRetractions(st.hasRetractions);
      setTime({ ms: st.totalTimeMs, src: st.timeEstimateSource });
      // If the chosen mode isn't available for this file, fall back to a mode that always is.
      if (!st.availableColorModes.includes(colorModeId) && colorModeReason(colorModeId, s.capabilities) !== '') {
        setColorModeId('single');
      }
    }
  }

  function refreshStats() {
    setStats(ref.current?.controls.getRenderStats() ?? null);
  }

  function onCanvasClick(e) {
    const c = e.currentTarget.querySelector('canvas');
    if (!c || layers === 0) return;
    const r = c.getBoundingClientRect();
    const ndcX = ((e.clientX - r.left) / r.width) * 2 - 1;
    const ndcY = -(((e.clientY - r.top) / r.height) * 2 - 1);
    // pickSegment returns the IR segment index, or null if the ray missed.
    setPicked(ref.current?.controls.pickSegment(ndcX, ndcY) ?? null);
  }

  const fx = FIXTURE_BY_ID[fixtureId];

  return (
    <>
      <header className="sc-header">
        <div className="sc-brand">
          <span className="gp-title">G-code Preview · React</span>
          <span className="gp-eyebrow">Showcase</span>
        </div>
        <select
          className="gp-input"
          style={{ width: 220 }}
          value={fixtureId}
          onChange={(e) => load(e.target.value)}
        >
          {FIXTURE_GROUPS.map((g) => (
            <optgroup key={g.group} label={g.group}>
              {g.items.map((i) => (
                <option key={i.id} value={i.id}>
                  {i.label}
                </option>
              ))}
            </optgroup>
          ))}
        </select>
        <button className="gp-btn gp-primary" onClick={() => load(fixtureId)}>
          Load
        </button>
        <div className="sc-spacer" />
        <div className="gp-segment" role="group" aria-label="Chrome theme">
          {['dark', 'light'].map((c) => (
            <button key={c} className={chrome === c ? 'gp-on' : ''} onClick={() => setChrome(c)}>
              {c === 'dark' ? 'Dark' : 'Light'}
            </button>
          ))}
        </div>
      </header>

      <div className="sc-main">
        <div className="sc-viewport" onClick={onCanvasClick}>
          <GcodePreview
            ref={ref}
            source={source}
            colorMode={colorMode}
            layerRange={layers > 0 ? [0, topLayer] : null}
            hiddenFeatureRoles={hideAdhesion ? ADHESION_ROLES : undefined}
            showTravel={showTravel}
            showRetractions={showRetractions}
            view={view}
            frameContent="object"
            quality="auto"
            onReady={onReady}
            onBuildComplete={refreshStats}
            onDisclosure={(t) => setDisclosure(t ?? '')}
            onParseError={(e) => setDisclosure(`Parse error: ${e.code} — ${e.message}`)}
          />
          {legend && (
            <div className="sc-legend-card">
              <span className="gp-eyebrow">{mode.label}</span>
              <div className="gp-legend">
                {legend.map(([label, rgb]) => (
                  <span className="gp-legend-item" key={label}>
                    <span className="gp-swatch" style={{ background: rgbCss(rgb) }} />
                    {label}
                  </span>
                ))}
              </div>
            </div>
          )}
          <div className="sc-cam">
            {CAM_VIEWS.map(([v, label]) => (
              <button
                key={v}
                className={`gp-icon-btn ${view === v ? 'gp-on' : ''}`}
                title={`${label} view`}
                onClick={() => setView(v)}
              >
                {label[0]}
              </button>
            ))}
          </div>
          {segments > 0 && (
            <div className="sc-count">
              {formatCount(segments)} segments · {layers} layers
              {time.ms !== null && ` · ${formatDuration(time.ms)}`}
            </div>
          )}
        </div>

        <aside className="sc-rail">
          <div className="gp-scroll">
            <section className="gp-panel">
              <h3>Appearance</h3>
              <div className="gp-field">
                <label htmlFor="mode">Color by</label>
                <select
                  id="mode"
                  className="gp-input"
                  value={colorModeId}
                  onChange={(e) => setColorModeId(e.target.value)}
                >
                  {COLOR_MODES.map((m) => {
                    const reason = colorModeReason(m.id, caps);
                    return (
                      <option key={m.id} value={m.id} disabled={reason !== ''}>
                        {m.label}
                        {reason !== '' ? ' — unavailable' : ''}
                      </option>
                    );
                  })}
                </select>
                {modeReason !== '' && <span className="gp-reason">{modeReason}</span>}
              </div>
            </section>

            <section className="gp-panel">
              <h3>Filter</h3>
              {layers > 0 && (
                <div className="gp-field">
                  <label>
                    Top layer <span className="gp-value">{topLayer} / {Math.max(0, layers - 1)}</span>
                  </label>
                  <input
                    className="gp-range"
                    type="range"
                    min={0}
                    max={Math.max(0, layers - 1)}
                    value={topLayer}
                    onChange={(e) => setTopLayer(Number(e.target.value))}
                  />
                </div>
              )}
              <label className={`gp-toggle ${featureRolesKnown ? '' : 'gp-disabled'}`}>
                <span>
                  Hide skirt &amp; brim
                  {!featureRolesKnown && <span className="gp-reason"> — file has no feature roles</span>}
                </span>
                <input
                  type="checkbox"
                  checked={hideAdhesion}
                  disabled={!featureRolesKnown}
                  onChange={(e) => setHideAdhesion(e.target.checked)}
                />
              </label>
              <label className="gp-toggle">
                <span>Show travel moves</span>
                <input type="checkbox" checked={showTravel} onChange={(e) => setShowTravel(e.target.checked)} />
              </label>
              <label className={`gp-toggle ${hasRetractions ? '' : 'gp-disabled'}`}>
                <span>
                  Show retractions
                  {!hasRetractions && <span className="gp-reason"> — none in this file</span>}
                </span>
                <input
                  type="checkbox"
                  checked={showRetractions}
                  disabled={!hasRetractions}
                  onChange={(e) => setShowRetractions(e.target.checked)}
                />
              </label>
            </section>

            <section className="gp-panel">
              <h3>Diagnostics</h3>
              <button className="gp-btn" onClick={refreshStats} disabled={segments === 0}>
                Read render stats
              </button>
              {stats && (
                <div style={{ marginTop: 'var(--gp-space-3)' }} className="gp-mono">
                  <div>backend: {stats.backend} ({stats.capability})</div>
                  <div>geometry: {stats.geometryMode}</div>
                  <div>segments: {formatCount(stats.renderedSegmentCount ?? 0)}</div>
                  <div>draw calls: {stats.drawCalls ?? '—'}</div>
                  {stats.gpuRenderer && <div style={{ color: 'var(--gp-text-faint)' }}>{stats.gpuRenderer}</div>}
                </div>
              )}
              {picked !== null && (
                <p className="gp-reason" style={{ marginTop: 'var(--gp-space-2)' }}>
                  Picked IR segment #{picked}
                </p>
              )}
              {picked === null && segments > 0 && (
                <p className="gp-reason" style={{ marginTop: 'var(--gp-space-2)' }}>
                  Click the model to identify a segment.
                </p>
              )}
            </section>
          </div>
        </aside>
      </div>

      <footer className="sc-status">
        <div className="sc-caps">
          {['featureRoles', 'objects', 'feedrate', 'colorChanges'].map((k) => {
            const tier = confidenceTier(caps[k]);
            return (
              <span key={k} className={`gp-badge ${tier.cls}`} title={`${k}: ${tier.label}`}>
                {k} · {tier.label}
              </span>
            );
          })}
        </div>
        <div className="sc-spacer" />
        <span>{disclosure || (fx ? fx.blurb : 'Pick a fixture to begin.')}</span>
      </footer>
    </>
  );
}

createRoot(document.getElementById('app')).render(
  <StrictMode>
    <App />
  </StrictMode>
);

// tools/example-vue/src/Showcase.vue
<!--
  Full showcase example (DD-031 §4.7, tier 2).

  Exercises the real declarative surface of @chestnutlabs/gcode-preview-vue and mirrors the Feature
  Lab's capability-aware UX in Vue idiom: color modes gate on the file's capabilities with a
  plain-language reason, feature-role hiding is a declarative binding, and diagnostics/picking come
  through the component ref's handle (`viewer.preview.controls`). Chrome (light/dark) is separate
  from the renderer's neutral viewport. Styling is the shared workspace-internal demo-kit — not a
  published UI kit and not a library default. Still the real package: no raw renderer imports.
-->
<script setup>
import { computed, ref, watchEffect } from 'vue';
import { GcodePreview } from '@chestnutlabs/gcode-preview-vue';
import { FeatureRole } from '@chestnutlabs/toolpath-core';
import {
  FIXTURE_GROUPS,
  FIXTURE_BY_ID,
  COLOR_MODES,
  COLOR_MODE_BY_ID,
  colorModeReason,
  confidenceTier,
  rgbCss,
  count as formatCount,
  duration as formatDuration
} from '../../demo-kit/index.js';

const ADHESION_ROLES = [FeatureRole.Skirt, FeatureRole.Brim];
const CAM_VIEWS = [
  ['iso', 'Iso'],
  ['top', 'Top'],
  ['front', 'Front']
];
const CAP_KEYS = ['featureRoles', 'objects', 'feedrate', 'colorChanges'];

const viewer = ref(null);
const chrome = ref('dark');
const fixtureId = ref('skirt-brim');
const source = ref(null);

// Reactive UI state, mirrored from the component's events (parallel to the other adapters' showcases;
// note that Vue's `viewer.preview.state` is itself reactive, so binding to it directly also works).
const caps = ref({});
const layers = ref(0);
const segments = ref(0);
const topLayer = ref(0);
const disclosure = ref('');
const hasRetractions = ref(false);
const time = ref({ ms: null, src: null });
const stats = ref(null);
const picked = ref(null);

// Declarative control state.
const colorModeId = ref('feature');
const hideAdhesion = ref(false);
const showTravel = ref(false);
const showRetractions = ref(false);
const view = ref('iso');

watchEffect(() => {
  document.documentElement.dataset.chrome = chrome.value;
});

const mode = computed(() => COLOR_MODE_BY_ID[colorModeId.value]);
const modeReason = computed(() => colorModeReason(colorModeId.value, caps.value));
const colorMode = computed(() => (modeReason.value === '' ? mode.value.build() : undefined));
const legend = computed(() => mode.value.legend ?? null);
const featureRolesKnown = computed(() => caps.value.featureRoles === 'known' || caps.value.featureRoles === 'inferred');
const hiddenRoles = computed(() => (hideAdhesion.value ? ADHESION_ROLES : undefined));
const fixture = computed(() => FIXTURE_BY_ID[fixtureId.value]);

async function load(id) {
  const fx = FIXTURE_BY_ID[id ?? fixtureId.value];
  if (!fx) return;
  fixtureId.value = fx.id;
  const res = await fetch(`./${fx.path}`);
  source.value = new Uint8Array(await res.arrayBuffer());
  stats.value = null;
  picked.value = null;
}

function onReady(summary) {
  caps.value = summary.capabilities;
  layers.value = summary.layers;
  segments.value = summary.segments;
  topLayer.value = Math.max(0, summary.layers - 1);
  if (typeof window !== 'undefined') window.gcodePreview = viewer.value?.preview; // for devtools/inspection
  const st = viewer.value?.preview?.state;
  if (st) {
    hasRetractions.value = st.hasRetractions;
    time.value = { ms: st.totalTimeMs, src: st.timeEstimateSource };
    if (!st.availableColorModes.includes(colorModeId.value) && colorModeReason(colorModeId.value, summary.capabilities) !== '') {
      colorModeId.value = 'single';
    }
  }
}

function refreshStats() {
  stats.value = viewer.value?.preview?.controls.getRenderStats() ?? null;
}

function onCanvasClick(e) {
  const c = e.currentTarget.querySelector('canvas');
  if (!c || layers.value === 0) return;
  const r = c.getBoundingClientRect();
  const ndcX = ((e.clientX - r.left) / r.width) * 2 - 1;
  const ndcY = -(((e.clientY - r.top) / r.height) * 2 - 1);
  // pickSegment returns the IR segment index, or null if the ray missed.
  picked.value = viewer.value?.preview?.controls.pickSegment(ndcX, ndcY) ?? null;
}

function modeDisabled(id) {
  return colorModeReason(id, caps.value) !== '';
}
</script>

<template>
  <header class="sc-header">
    <div class="sc-brand">
      <span class="gp-title">G-code Preview · Vue</span>
      <span class="gp-eyebrow">Showcase</span>
    </div>
    <select class="gp-input" style="width: 220px" :value="fixtureId" @change="load($event.target.value)">
      <optgroup v-for="g in FIXTURE_GROUPS" :key="g.group" :label="g.group">
        <option v-for="i in g.items" :key="i.id" :value="i.id">{{ i.label }}</option>
      </optgroup>
    </select>
    <button class="gp-btn gp-primary" @click="load()">Load</button>
    <div class="sc-spacer" />
    <div class="gp-segment" role="group" aria-label="Chrome theme">
      <button :class="chrome === 'dark' ? 'gp-on' : ''" @click="chrome = 'dark'">Dark</button>
      <button :class="chrome === 'light' ? 'gp-on' : ''" @click="chrome = 'light'">Light</button>
    </div>
  </header>

  <div class="sc-main">
    <div class="sc-viewport" @click="onCanvasClick">
      <GcodePreview
        ref="viewer"
        :source="source"
        :color-mode="colorMode"
        :layer-range="layers > 0 ? [0, topLayer] : null"
        :hidden-feature-roles="hiddenRoles"
        :show-travel="showTravel"
        :show-retractions="showRetractions"
        :view="view"
        frame-content="object"
        quality="auto"
        @ready="onReady"
        @build-complete="refreshStats"
        @disclosure="disclosure = $event ?? ''"
        @parse-error="disclosure = `Parse error: ${$event.code} — ${$event.message}`"
      />
      <div v-if="legend" class="sc-legend-card">
        <span class="gp-eyebrow">{{ mode.label }}</span>
        <div class="gp-legend">
          <span v-for="[label, rgb] in legend" :key="label" class="gp-legend-item">
            <span class="gp-swatch" :style="{ background: rgbCss(rgb) }" />
            {{ label }}
          </span>
        </div>
      </div>
      <div class="sc-cam">
        <button
          v-for="[v, label] in CAM_VIEWS"
          :key="v"
          class="gp-icon-btn"
          :class="view === v ? 'gp-on' : ''"
          :title="`${label} view`"
          @click="view = v"
        >
          {{ label[0] }}
        </button>
      </div>
      <div v-if="segments > 0" class="sc-count">
        {{ formatCount(segments) }} segments · {{ layers }} layers
        <template v-if="time.ms !== null"> · {{ formatDuration(time.ms) }}</template>
      </div>
    </div>

    <aside class="sc-rail">
      <div class="gp-scroll">
        <section class="gp-panel">
          <h3>Appearance</h3>
          <div class="gp-field">
            <label for="mode">Color by</label>
            <select id="mode" class="gp-input" v-model="colorModeId">
              <option v-for="m in COLOR_MODES" :key="m.id" :value="m.id" :disabled="modeDisabled(m.id)">
                {{ m.label }}{{ modeDisabled(m.id) ? ' — unavailable' : '' }}
              </option>
            </select>
            <span v-if="modeReason !== ''" class="gp-reason">{{ modeReason }}</span>
          </div>
        </section>

        <section class="gp-panel">
          <h3>Filter</h3>
          <div v-if="layers > 0" class="gp-field">
            <label>Top layer <span class="gp-value">{{ topLayer }} / {{ Math.max(0, layers - 1) }}</span></label>
            <input class="gp-range" type="range" :min="0" :max="Math.max(0, layers - 1)" v-model.number="topLayer" />
          </div>
          <label class="gp-toggle" :class="featureRolesKnown ? '' : 'gp-disabled'">
            <span>
              Hide skirt &amp; brim
              <span v-if="!featureRolesKnown" class="gp-reason"> — file has no feature roles</span>
            </span>
            <input type="checkbox" v-model="hideAdhesion" :disabled="!featureRolesKnown" />
          </label>
          <label class="gp-toggle">
            <span>Show travel moves</span>
            <input type="checkbox" v-model="showTravel" />
          </label>
          <label class="gp-toggle" :class="hasRetractions ? '' : 'gp-disabled'">
            <span>
              Show retractions
              <span v-if="!hasRetractions" class="gp-reason"> — none in this file</span>
            </span>
            <input type="checkbox" v-model="showRetractions" :disabled="!hasRetractions" />
          </label>
        </section>

        <section class="gp-panel">
          <h3>Diagnostics</h3>
          <button class="gp-btn" @click="refreshStats" :disabled="segments === 0">Read render stats</button>
          <div v-if="stats" class="gp-mono" style="margin-top: var(--gp-space-3)">
            <div>backend: {{ stats.backend }} ({{ stats.capability }})</div>
            <div>geometry: {{ stats.geometryMode }}</div>
            <div>segments: {{ formatCount(stats.renderedSegmentCount ?? 0) }}</div>
            <div>draw calls: {{ stats.drawCalls ?? '—' }}</div>
            <div v-if="stats.gpuRenderer" style="color: var(--gp-text-faint)">{{ stats.gpuRenderer }}</div>
          </div>
          <p v-if="picked !== null" class="gp-reason" style="margin-top: var(--gp-space-2)">
            Picked IR segment #{{ picked }}
          </p>
          <p v-else-if="segments > 0" class="gp-reason" style="margin-top: var(--gp-space-2)">
            Click the model to identify a segment.
          </p>
        </section>
      </div>
    </aside>
  </div>

  <footer class="sc-status">
    <div class="sc-caps">
      <span
        v-for="k in CAP_KEYS"
        :key="k"
        class="gp-badge"
        :class="confidenceTier(caps[k]).cls"
        :title="`${k}: ${confidenceTier(caps[k]).label}`"
      >
        {{ k }} · {{ confidenceTier(caps[k]).label }}
      </span>
    </div>
    <div class="sc-spacer" />
    <span>{{ disclosure || (fixture ? fixture.blurb : 'Pick a fixture to begin.') }}</span>
  </footer>
</template>
